# SPDX-License-Identifier: GPL-2.0

pancsf-y := \
	pancsf_devfreq.o \
	pancsf_device.o \
	pancsf_drv.o \
	pancsf_gem.o \
	pancsf_gpu.o \
	pancsf_heap.o \
	pancsf_heap.o \
	pancsf_mcu.o \
	pancsf_mmu.o \
	pancsf_sched.o

obj-$(CONFIG_DRM_PANCSF) += pancsf.o
