# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_BCMDHD)	+= rkwifi/
obj-$(CONFIG_CYW_BCMDHD)	+= cywdhd/
obj-$(CONFIG_INFINEON_DHD)	+= infineon/

obj-$(CONFIG_RTL8852BE)		+= rtl8852be/
obj-$(CONFIG_RTL8852BU)		+= rtl8852bu/
obj-$(CONFIG_RTL8821CU_RK)	+= rtl8821cu/
obj-$(CONFIG_RTL8723DS_RK)	+= rtl8723ds/
obj-$(CONFIG_RTL8723DU_RK)	+= rtl8723du/
